### ISSUE TITLE
Can't display the person who used the invitation code normally (probably caused by me)

### ISSUE THREAD

**Issue by Le0nsec** [h4ckd0tm3/ctfd-bouncer#1]
In the process of use, I found that the user_id column in the bouncer_uses table stored in the database does not work properly, and always displays null. It may be the cause of my version. Can your version display the user_id normally?
![](https://s1.ax1x.com/2020/07/17/Us7t58.png)

**Comment by Le0nsec** [comment]
My CTFd Version:2.5.0

**Comment by h4ckd0tm3** [comment]
I'm on 2.5.0 too. Did not verify if the column was empty. Will check! Thank you!

**Comment by h4ckd0tm3** [comment]
Should be fixed. :)
